### ISSUE TITLE
Cross-table URI transformation

### ISSUE THREAD

**Issue by shipeifan** [aws/amazon-neptune-csv-to-rdf-converter#13]
Hello！I would like to ask you a question about cross-table URI transformation.
The scene is as follows: Here are two node tables (or two node csv files) , both of which have ~ids columns starting from 0, and there is an edge table generated from these two node tables. When I try to perform a uri transformation on this edge file, the following error is reported:
```
-->Extracting URI transformation resources and replacement values from xxx.nq...
CSV to RDF conversion failed.
Found duplicate, inconsistent value for <http://dbpedia.org/resource/0>: Hamid_Karzai vs. Thing
```
I understand that the same id and prefix in both node files is causing this problem, but the id column of a node file usually starts from 0 and inevitably get duplicated. Is there any good way to solve this problem? I hope to get your reply, thank you very much.

**Comment by triggan** [comment]
The original intent of this utility is to convert property graph data (represented in the native CSV format used by Neptune's bulk load feature [1]) into an RDF representation of the same graph.  Neptune's property graph implementation requires that every node/vertex ID must be unique.  So if you have duplicate representations of the same node/vertex within the two node files, you'll need to reconcile those first before doing the conversion.

[1] https://docs.aws.amazon.com/neptune/latest/userguide/bulk-load-tutorial-format-gremlin.html

**Comment by shipeifan** [comment]
> The original intent of this utility is to convert property graph data (represented in the native CSV format used by Neptune's bulk load feature [1]) into an RDF representation of the same graph. Neptune's property graph implementation requires that every node/vertex ID must be unique. So if you have duplicate representations of the same node/vertex within the two node files, you'll need to reconcile those first before doing the conversion.
> 
> [1] https://docs.aws.amazon.com/neptune/latest/userguide/bulk-load-tutorial-format-gremlin.html

OK, I got it. Thanks a lot.
